services:
  pyroscope:
    # fixed versions for pyroscope, otel-collector, otel-profiler due to protocol changes
    image: grafana/pyroscope:1.15.0
    command: ["-self-profiling.disable-push=true"]
    ports:
      - "4040:4040"
    networks:
      - otel-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.141.0
    command: ["--config=/etc/otel-collector-config.yaml", "--feature-gates=service.profilesSupport"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - otel-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
