---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    gadgetImage: "profile_cuda:main"
  labels:
    name: profile-cuda
    type: gadget-instance
  name: profile-cuda
  namespace: gpu-observability
immutable: true
data:
  data:
  operator.KubeManager.all-namespaces: "false"
  operator.KubeManager.namespace: "default"
  operator.oci.ebpf.collect-ustack: "true"
  operator.otel-profiles.otel-profiles-exporter: "my-profiles-exporter"
