---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    gadgetImage: "ghcr.io/inspektor-gadget/gadget/top_cuda_memory"
  labels:
    name: top-cuda-memory
    type: gadget-instance
  name: top-cuda-memory
  namespace: {{ .Release.Namespace }}
data:
  operator.KubeManager.all-namespaces: "false"
  operator.KubeManager.namespace: "default"
  operator.otel-metrics.otel-metrics-name: "libcuda_mem_stats:libcuda_mem_stats,libcudart_mem_stats:libcudart_mem_stats"
  operator.oci.annotate: "libcuda_mem_stats.k8s.podName:metrics.type=key"
