services:
  pyroscope:
    # fixed versions for pyroscope, otel-collector, otel-profiler due to protocol changes
    image: grafana/pyroscope:1.15.0
    command: ["-self-profiling.disable-push=true"]
    ports:
      - "4040:4040"
    networks:
      - otel-net

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - otel-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - otel-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ig_profile_cuda:
    image: ghcr.io/inspektor-gadget/ig:latest
    command: run  profile_cuda:main --verify-image=false --config=/config.yaml --otel-profiles-exporter=my-profiles-exporter --collect-ustack=true --host
    volumes:
      - ./ig/config.yaml:/config.yaml
      - /:/host
    privileged: true
    networks:
      - otel-net

  ig_cuda_memory_metrics:
    image: ghcr.io/inspektor-gadget/ig:latest
    command: run ghcr.io/mqasimsarfraz/gadget/cuda_memory_metrics:burak-cuda-mem_metrics --verify-image=false --config=/config.yaml --pull=always --otel-metrics-listen=true --host --otel-metrics-name=libcuda_mem_stats:libcuda_mem_stats,libcudart_mem_stats:libcudart_mem_stats
    volumes:
      - ./ig/config.yaml:/config.yaml
      - /:/host
    ports:
      - "2224:2224"
    privileged: true
    networks:
      - otel-net

  cuda_sample_tf_mnist:
    image: mcr.microsoft.com/azuredocs/samples-tf-mnist-demo:gpu
    command: ["--max_steps", "500"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
