operator:
  otel-profiles:
    exporters:
      my-profiles-exporter:
        exporter: otlp-grpc
        compression: gzip
        # pyroscope
        endpoint: "127.0.0.1:4040"
        insecure: true
