apiVersion: v1
kind: Pod
metadata:
  name: gpu-testload
  namespace: default
  labels:
    app: gpu-testload
spec:
  restartPolicy: Never
  containers:
    - name: gpu-testload
      image: ghcr.io/inspektor-gadget/testgpu:latest
      # Set to IfNotPresent when using a locally built image,
      # change to Always if pushing to a registry.
      imagePullPolicy: Always
      args: ["python", "main.py", "--duration", "120", "--interval", "1", "--max-mb", "256"]
      resources:
        limits:
          nvidia.com/gpu: "1"
