apiVersion: v2
name: gpu-observability
description: Umbrella chart deploying Inspektor Gadget, OpenTelemetry Collector, Pyroscope, and Grafana
type: application
version: 0.1.0

dependencies:
  - name: gadget
    alias: inspektor-gadget
    version: "1.0.0-dev"
    repository: "oci://ghcr.io/inspektor-gadget/inspektor-gadget/charts"
  - name: pyroscope
    alias: pyroscope
    version: "1.15.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus
    alias: prometheus
    version: ">=0.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
