inspektor-gadget:
  image:
    tag: "mauricio-profile-cuda-rebased"
    repository: "ghcr.io/mauriciovasquezbernal/inspektor-gadget"
  hostPID: true
  nodeSelector:
    # Only deploy on nodes with GPU.
    accelerator: "nvidia"
  config:
    daemonLogLevel: info
    operator:
      otel-profiles:
        exporters:
          my-profiles-exporter:
            exporter: otlp-grpc
            compression: gzip
            endpoint: gpu-observability-pyroscope-distributor.gpu-observability.svc.cluster.local:4040
            insecure: true
      otel-metrics:
        otel-metrics-listen: true
        otel-metrics-listen-address: "0.0.0.0:2224"
      oci:
        verify-image: false

pyroscope:
  alloy:
    enabled: false
  architecture:
    microservices:
      enabled: true
    # Better than v1 for scaling.
    storage:
      v2: true
  minio:
    enabled: false
  pyroscope:
    # Other components are defined in value-micro-services.yaml taken from:
    # https://github.com/grafana/pyroscope/blob/318871de4599/operations/pyroscope/helm/pyroscope/values-micro-services.yaml
    # Having split components helps scaling.
    components:
      ad-hoc-profiles:
        # We only want to profile using Inspektor Gadget.
        replicaCount: 0
      querier:
        # We only have one node for now.
        replicaCount: 1
      query-frontend:
        replicaCount: 1
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-pls-create: "true"
            service.beta.kubernetes.io/azure-pls-name: "pyroscope-pls"
            service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
            # Everyone can see it, but this does not mean they can access it.
            service.beta.kubernetes.io/azure-pls-visibility: "*"
      query-scheduler:
        replicaCount: 1
    # The image must be set here and not in upper level. Otherwise, 1.14.0 would
    # be used and communication would not occur.
    # Thanks Mauricio for spotting this!
    image:
      repository: grafana/pyroscope
      tag: "1.15.0"
    structuredConfig:
      self_profiling:
        disable_push: true
      storage:
        backend: filesystem
  service:
    port: 4040
prometheus:
  server:
    global:
      scrape_interval: 15s
      scrape_timeout: 5s
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/azure-pls-create: "true"
        service.beta.kubernetes.io/azure-pls-name: "prometheus-pls"
        service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
        # Everyone can see it, but this does not mean they can access it.
        service.beta.kubernetes.io/azure-pls-visibility: "*"
  kube-state-metrics:
    enabled: false
  alertmanager:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  scrapeConfigs:
    - job_name: 'inspektor-gadget'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - gpu-observability
      relabel_configs:
        # Only keep pods with label k8s-app=gadget
        - source_labels: [ __meta_kubernetes_pod_label_k8s_app ]
          action: keep
          regex: gadget
        # Force metrics path
        - target_label: __metrics_path__
          replacement: /metrics
        # Force port
        - source_labels: [ __address__ ]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: $1:2224
          target_label: __address__
